config/routes.rb
PrintchompPrototype::Application.routes.draw do

  get "home/index"
  
  get "quotes/index"
  get "quotes/details"

  get "orders/index"
  get "orders/details"
  
  get "offers/index"

  get "statistics/index"

  get "products/index"

  root :to => 'home#index'
  
  resources :quotes
  
  resources :orders
  resources :products
  resources :offers
  resources :statistics

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def details
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end
  
  def details
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
  end
  
  def details
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/home/index.slim
section#content-main
  .h1-header-main
    h1 Statistics
    
  ul.tabs
    li.active
      a href="#week" data-toggle="tab" This Week      
    li
      a href="#month" data-toggle="tab" This Month
    li
      a href="#year" data-toggle="tab" This Year
      
  .tab-content
    .tab-pane.active#week
      = image_tag "stats.png", class: "stats-img";
    .tab-pane#month
      = image_tag "stats.png", class: "stats-img";
    .tab-pane#year
      = image_tag "stats.png", class: "stats-img";
      
  .h1-header-main.border-top
    h1 Activity Feed    
    
  ul.tabs
    li.active
      a href="#quotes" data-toggle="tab" Quotes      
    li
      a href="#shipped" data-toggle="tab" Shipped
    li
      a href="#delivered" data-toggle="tab" Delivered
    li
      a href="#rejected" data-toggle="tab" Rejected
      
  .tab-content.no-padding
    .tab-pane.active#quotes
      table.tbl-order
        tbody
          tr
            td 
              .td-label Order
              .td-desc 1234
            td
              .td-label Product
              .td-desc Business Cards
            td
              .td-label Customer
              .td-desc Diane Smith
            td
              .td-label Status
              .td-desc Awaiting Response
            td.text-right
              = link_to "Quote", quotes_details_path, class: "btn-red" 
                /i.fa.fa-angle-right.fa-2x

          tr
            td 
              .td-label Order
              .td-desc 1238
            td
              .td-label Product
              .td-desc Vinyl Stickers
            td
              .td-label Customer
              .td-desc Diane Smith
            td
              .td-label Status
              .td-desc Awaiting Response
            td.text-right
              = link_to "Quote", quotes_details_path, class: "btn-red"  
              /i.fa.fa-angle-right.fa-2x
                                
          tr
            td 
              .td-label Order
              .td-desc 1240
            td
              .td-label Product
              .td-desc Business Cards
            td
              .td-label Customer
              .td-desc Eva Mendes
            td
              .td-label Status
              .td-desc Awaiting Response
            td.text-right
              = link_to "Quote", quotes_details_path, class: "btn-red"  
              /i.fa.fa-angle-right.fa-2x
              
    .tab-pane#shipped
      table.tbl-order 
        tbody
          tr
            td 
              .td-label Order
              .td-desc 1218
            td
              .td-label Product
              .td-desc Business Cards
            td
              .td-label Customer
              .td-desc Diane Smith
            td
              .td-label Status
              .td-desc Shipped
            td.text-right
              = link_to "Details", quotes_details_path 
                /i.fa.fa-angle-right.fa-2x
      
      
    .tab-pane#delivered
      table.tbl-order
        tbody
          tr
            td 
              .td-label Order
              .td-desc 1200
            td
              .td-label Product
              .td-desc Business Cards
            td
              .td-label Customer
              .td-desc Diane Smith
            td
              .td-label Status
              .td-desc Delivered
            td.text-right
              = link_to "Details", quotes_details_path 
                /i.fa.fa-angle-right.fa-2x
      
    .tab-pane#rejected
      .no-msg
        p You currently don't have any Rejected Quotes or Orders. Great job!
          

section#content-secondary
  .h1-header-secondary
    h1 Messages
    
  .msg-toggle
    ul.nav
      li.dropdown
        a.dropdown-toggle data-toggle="dropdown" href="#" 
          |
            All 
          span.caret
          
        ul.dropdown-menu
          li
            a href="#" All
          li
            a href="#" Quotes
          li
            a href="#" Orders  
  
  .msg
    p.from Diane Smith
    p.id Quote 1234
    p.msg-body I've uploaded my artwork.
    p.time 1 hr ago
    
    a.link href="/quotes/details"
      i.fa.fa-angle-right.fa-2x
      
  .msg
    p.from Diane Smith
    p.id Quote 1238
    p.msg-body 
      | I've decided I'd like to pickup my order versus having it Shipped. Can you provide me with an updated price? Thanks
    p.time 1 hr ago

    a.link href="/quotes/details"
      i.fa.fa-angle-right.fa-2x    
      
  .msg
    p.from Eva Mendes
    p.id Quote 1240
    p.msg-body 
      | We received our order and are extremely happy with the result. Thanks again. Diane
    p.time 1 hr ago

    a.link href="/quotes/details"
      i.fa.fa-angle-right.fa-2x
      

app/views/layouts/application.slim
doctype html
html
  head
    title Printchomp
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    =stylesheet_link_tag "application"
    =javascript_include_tag "application"
        
  body 
  
    .container-fluid
      header id="header"
        h1 Printchomp
      
      section#content
        #sidebar

          .printer-info
            .logo
            h1 Business Ninja
            a http://www.businessninja.com
            
          p.profile-completeness Profile Completeness  
          .progress
            .progress-bar role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"
              span.sr-only 60% Complete
        
          nav#navigation 
            ul
              li
                = active_link_to "Dashboard", root_path
              li
                = active_link_to "Orders", orders_path
              li
                = active_link_to "Quotes", quotes_path
              li
                = active_link_to "Products", products_path
              li
                = active_link_to "Offers", offers_path
              li
                = active_link_to "Statistics", statistics_path
        
        == yield

app/views/offers/index.slim
section#content-main
  .h1-header-main
    h1 Offers

  .content
    p What would you expect when you land on this page?

app/views/orders/details.slim
section#tertiary
  section#content-main
    .h1-header-main.border-top
      h1 Order - Business Cards

    .alert-success Order has been Approved.
    
    .details-row
      p.details-label Printed By
      p.details-desc Printchomp Milton

    .details-row
      p.details-label Order Placed
      p.details-desc April 2, 2014
  
    .details-row
      p.details-label Product
      p.details-desc Business Cards
  
    .details-row
      p.details-label Material
      p.details-desc 12pt Glossy
  
    .details-row
      p.details-label Size
      p.details-desc 3.5" x 2.5"
  
    .details-row
      p.details-label Quantity
      p.details-desc 500
  
    .details-row
      p.details-label Options
      .details-desc 
        ul
          li 2-sided
          li AQ Coating
      
    .details-row
      p.details-label Email
      p.details-desc diane.smith@gmail.com
      
    .details-row
      p.details-label Phone
      p.details-desc 123.456.7890
  
    .details-row
      p.details-label Artwork
      p.details-desc 
        a href="#" Business Card.pdf
    
    .details-row
      p.details-label 
        a.link href="#" Download to CSV
      p.details-desc 
    


  section#content-tertiary
    .h1-header-tertiary
      h1 Actions
      
    .shipping-address  
      h2 Shipping Address
      address
        p 1 King St. 
        p Waterloo, Ontario Canada
        p N2M 0A1
      
    form.response role="form"
      .form-group
        label Tracking Number
        input.form-control type="text"

    .text-center    
      button.btn-green data-toggle="modal" data-target="#send-response" Save

  section#content-secondary
    .h1-header-secondary
      h1 Messages
  
    .msg
      p.from Diane Smith
      p.id Quote 1234
      p.msg-body I've uploaded my artwork.
      p.time 1 hr ago
    
      a.link href="#"
        i.fa.fa-angle-right.fa-2x
      
    .msg
      p.from Diane Smith
      p.id Quote 1234
      p.msg-body 
        | I've decided I'd like to pickup my order versus having it Shipped. Can you provide me with an updated price? Thanks
      p.time 1 hr ago

      a.link href="#"
        i.fa.fa-angle-right.fa-2x
        

app/views/orders/index.slim
section#content-main
  .h1-header-main.border-top
    h1 Orders    
    
  ul.tabs
    li.active
      a href="#orders" data-toggle="tab" Orders      
    li
      a href="#shipped" data-toggle="tab" Shipped
    li
      a href="#delivered" data-toggle="tab" Delivered
    li
      a href="#rejected" data-toggle="tab" Rejected
      
  .tab-content.no-padding
    .tab-pane.active#orders
      table.tbl-order
        tbody
          tr
            td 
              .td-label Order
              .td-desc 1237
            td
              .td-label Product
              .td-desc Business Cards
            td
              .td-label Customer
              .td-desc Diane Smith
            td
              .td-label Status
              .td-desc Awaiting Response
            td.text-right
              = link_to "Details", orders_details_path 
                /i.fa.fa-angle-right.fa-2x

          tr
            td 
              .td-label Order
              .td-desc 1244
            td
              .td-label Product
              .td-desc Vinyl Stickers
            td
              .td-label Customer
              .td-desc Diane Smith
            td
              .td-label Status
              .td-desc Awaiting Response
            td.text-right
              = link_to "Details", orders_details_path 
                /i.fa.fa-angle-right.fa-2x
                                
          tr
            td 
              .td-label Order
              .td-desc 1241
            td
              .td-label Product
              .td-desc Business Cards
            td
              .td-label Customer
              .td-desc Eva Mendes
            td
              .td-label Status
              .td-desc Awaiting Response
            td.text-right
              = link_to "Details", orders_details_path 
                /i.fa.fa-angle-right.fa-2x
              
    .tab-pane#shipped
       table.tbl-order
          tbody
            tr
              td 
                .td-label Order
                .td-desc 1218
              td
                .td-label Product
                .td-desc Business Cards
              td
                .td-label Customer
                .td-desc Diane Smith
              td
                .td-label Status
                .td-desc Shipped
              td.text-right
                = link_to "Details", orders_details_path 
                  /i.fa.fa-angle-right.fa-2x
                  
    .tab-pane#delivered
      table.tbl-order
        tbody
          tr
            td 
              .td-label Order
              .td-desc 1200
            td
              .td-label Product
              .td-desc Business Cards
            td
              .td-label Customer
              .td-desc Diane Smith
            td
              .td-label Status
              .td-desc Delivered
            td.text-right
              = link_to "Details", orders_details_path 
                /i.fa.fa-angle-right.fa-2x
                
    .tab-pane#rejected
      .no-msg
        p You currently don't have any Rejected Quotes or Orders. Great job!
          
          

section#content-secondary
  .h1-header-secondary
    h1 Messages
    
  .msg-toggle
    ul.nav
      li.dropdown
        a.dropdown-toggle data-toggle="dropdown" href="#" 
          |
            Orders
          span.caret
          
        ul.dropdown-menu
          li
            a href="#" All
          li
            a href="#" Quotes
          li
            a href="#" Orders  
  
  .msg
    p.from Diane Smith
    p.id Quote 1234
    p.msg-body I've uploaded my artwork.
    p.time 1 hr ago
    
    a.link href="/orders/details"
      i.fa.fa-angle-right.fa-2x
      
  .msg
    p.from Diane Smith
    p.id Quote 1238
    p.msg-body 
      | I've decided I'd like to pickup my order versus having it Shipped. Can you provide me with an updated price? Thanks
    p.time 1 hr ago

    a.link href="/orders/details"
      i.fa.fa-angle-right.fa-2x
      
  .msg
    p.from Eva Mendes
    p.id Quote 1240
    p.msg-body 
      | We received our order and are extremely happy with the result. Thanks again. Diane
    p.time 1 hr ago

    a.link href="/orders/details"
      i.fa.fa-angle-right.fa-2x

app/views/products/index.slim
section#content-main
  .h1-header-main
    h1 Products

  .content
    p What would you expect when you land on this page?

app/views/quotes/details.slim
section#tertiary
  section#content-main
    .h1-header-main.border-top
      h1 Quote - Business Cards

    .quote-details
      .details-row.working-on-it
        p.details-label Are you working on this?
        p.details-desc.btn-toggle.no
          = image_tag("no-btn.png")
        p.details-desc.btn-toggle.yes.hide
          = image_tag("yes-btn.png")

      .details-row
        p.details-label Requested
        p.details-desc April 2, 2014
  
      .details-row
        p.details-label Needed by
        p.details-desc April 15, 2014
  
      .details-row
        p.details-label Product
        p.details-desc Business Cards
  
      .details-row
        p.details-label Material
        p.details-desc 12pt Glossy
  
      .details-row
        p.details-label Size
        p.details-desc 3.5" x 2.5"
  
      .details-row
        p.details-label Quantity
        p.details-desc 500
  
      .details-row
        p.details-label Options
        .details-desc 
          ul
            li 2-sided
            li AQ Coating
  
      .details-row
        p.details-label Ship to
        p.details-desc Kitchener, Ontario, Canada
  
      .details-row
        p.details-label Artwork
        p.details-desc.warning No Artwork
  
      .details-row
        p.details-label 
          a.link href="#reject" data-toggle="modal" data-target="#reject" Reject
        p.details-desc 


  section#content-tertiary
    .h1-header-tertiary
      h1 Response
      
    form.response role="form"
      .form-group
        label Price
        input.form-control.dollar-sign type="text" id="price" value="50.00"
      
      .form-group
        label Shipping 
        input.form-control.dollar-sign type="text" id="shipping" value="0.00"
      
      .form-group
        label Sales Tax
        input.form-control.dollar-sign type="text" id="tax" value="5.00"
        
      .total  
        p Total
        p.cost $55.00 /CAD
      
      .form-group
        label Branch
        select.form-control type="text"
          option Select Branch
          option Branch Name Goes Here
      
      .form-group
        label Pickup Date
        input.form-control type="text" value="April 25, 2014"

    .text-center    
      button#save-response.btn-green data-toggle="modal" data-target="#send-response" Send Response

  section#content-secondary
    .h1-header-secondary
      h1 Messages for Quote 1234
  
    .msg
      p.from Diane Smith
      p.msg-body I've uploaded my artwork.
      p.time 1 hr ago
      
    .msg
      p.from Diane Smith
      p.msg-body 
        | I've decided I'd like to pickup my order versus having it Shipped. Can you provide me with an updated price? Thanks
      p.time 1 hr ago
        
    .type-msg
      input.form-control type="text" placeholder="Type your message here"

.modal.fade#send-response tabindex="-1" role="dialog" aria-hidden="true" aria-labelledby="sendResponse"
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" aria-hidden="true" &times;
        h4 Send Response
        
      .modal-body
        p.alert-success Your response was sent successfully
        
        p Would you like to save this price for future orders?
        
        .details-row
          p.details-label Product
          p.details-desc Business Cards

        .details-row
          p.details-label Material
          p.details-desc 12pt Glossy

        .details-row
          p.details-label Size
          p.details-desc 3.5" x 2.5"

        .details-row
          p.details-label Quantity
          p.details-desc 500

        .details-row
          p.details-label Options
          .details-desc 
            ul
              li 2-sided
              li AQ Coating

        .details-row
          p.details-label Ship to
          p.details-desc Kitchener, Ontario, Canada
        
        .details-row
          .details-label Price
          .details-desc.modal-price $50.00
          
        .details-row
          .details-label Shipping
          .details-desc.modal-shipping $0.00
          
        .details-row
          .details-label Sales Tax
          .details-desc.modal-tax $5.00
          
        .details-row
          .details-label Total
          .details-desc.modal-total $55.00/CAD  
      
      .modal-footer
        button.btn-green.btn-default type="button" data-dismiss="modal" aria-hidden="true" Yes
        button.btn-red.btn-primary type="button" data-dismiss="modal" aria-hidden="true" No


.modal.fade#reject tabindex="-1" role="dialog" aria-hidden="true" aria-labelledby="reject"
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" aria-hidden="true" &times;
        h4 Reject Quote

      .modal-body
        p Are you sure you want to Reject this Quote?
        
        .details-row
          p.details-label Product
          p.details-desc Business Cards

        .details-row
          p.details-label Material
          p.details-desc 12pt Glossy

        .details-row
          p.details-label Size
          p.details-desc 3.5" x 2.5"

        .details-row
          p.details-label Quantity
          p.details-desc 500

        .details-row
          p.details-label Options
          .details-desc 
            ul
              li 2-sided
              li AQ Coating

        .details-row
          p.details-label Ship to
          p.details-desc Kitchener, Ontario, Canada

      .modal-footer
        button.btn-green type="button" data-dismiss="modal" aria-hidden="true" Yes
        button.btn-red type="button" data-dismiss="modal" aria-hidden="true" No

app/views/quotes/index.slim
section#content-main
  .h1-header-main.border-top
    h1 Quotes    
    
  ul.tabs
    li.active
      a href="#awaiting" data-toggle="tab" Awaiting Response     
    li
      a href="#quoted" data-toggle="tab" Quoted
    li
      a href="#cancelled" data-toggle="tab" Cancelled
    li
      a href="#rejected" data-toggle="tab" Rejected
      
  .tab-content.no-padding
    .tab-pane.active#awaiting
      table.tbl-order
        tbody
          tr
            td 
              .td-label Order
              .td-desc 1234
            td
              .td-label Product
              .td-desc Business Cards
            td
              .td-label Customer
              .td-desc Diane Smith
            td
              .td-label Status
              .td-desc Awaiting Response
            td.text-right
              = link_to "Quote", quotes_details_path, class: "coa-link"  
                /i.fa.fa-angle-right.fa-2x
                
          tr
            td 
              .td-label Order
              .td-desc 1238
            td
              .td-label Product
              .td-desc Vinyl Stickers
            td
              .td-label Customer
              .td-desc Diane Smith
            td
              .td-label Status
              .td-desc Awaiting Response
            td.text-right
              = link_to "Quote", quotes_details_path, class: "coa-link" 
                /i.fa.fa-angle-right.fa-2x
                                
          tr
            td 
              .td-label Order
              .td-desc 1240
            td
              .td-label Product
              .td-desc Business Cards
            td
              .td-label Customer
              .td-desc Eva Mendes
            td
              .td-label Status
              .td-desc Awaiting Response
            td.text-right
              = link_to "Quote", quotes_details_path, class: "coa-link"  
                /i.fa.fa-angle-right.fa-2x
              
    .tab-pane#quoted
       table.tbl-order
          tbody
            tr
              td 
                .td-label Order
                .td-desc 1218
              td
                .td-label Product
                .td-desc Business Cards
              td
                .td-label Customer
                .td-desc Diane Smith
              td
                .td-label Status
                .td-desc Quoted
              td.text-right
                = link_to "Details", quotes_details_path 
                  /i.fa.fa-angle-right.fa-2x
                  
    .tab-pane#cancelled
      table.tbl-order
        tbody
          tr
            td 
              .td-label Order
              .td-desc 1200
            td
              .td-label Product
              .td-desc Business Cards
            td
              .td-label Customer
              .td-desc Diane Smith
            td
              .td-label Status
              .td-desc Cancelled
            td.text-right
              = link_to "Details", quotes_details_path 
                /i.fa.fa-angle-right.fa-2x
                
    .tab-pane#rejected
      .no-msg
        p You currently don't have any Rejected Quotes or Orders. Great job!
          
          

section#content-secondary
  .h1-header-secondary
    h1 Messages
    
  .msg-toggle
    ul.nav
      li.dropdown
        a.dropdown-toggle data-toggle="dropdown" href="#" 
          |
            Quotes 
          span.caret
          
        ul.dropdown-menu
          li
            a href="#" All
          li
            a href="#" Quotes
          li
            a href="#" Orders  
  
  .msg
    p.from Diane Smith
    p.id Quote 1234
    p.msg-body I've uploaded my artwork.
    p.time 1 hr ago
    
    a.link href="/quotes/details"
      i.fa.fa-angle-right.fa-2x
      
  .msg
    p.from Diane Smith
    p.id Quote 1238
    p.msg-body 
      | I've decided I'd like to pickup my order versus having it Shipped. Can you provide me with an updated price? Thanks
    p.time 1 hr ago

    a.link href="/quotes/details"
      i.fa.fa-angle-right.fa-2x
      
  .msg
    p.from Eva Mendes
    p.id Quote 1240
    p.msg-body 
      | We received our order and are extremely happy with the result. Thanks again. Diane
    p.time 1 hr ago

    a.link href="/quotes/details"
      i.fa.fa-angle-right.fa-2x

app/views/statistics/index.slim
section#content-main
  .h1-header-main
    h1 Statistics

  .content
    p What would you expect when you land on this page?